//
// This path was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this path will be lost upon recompilation of the source schema.
// Generated on: 2010.03.15 at 03:58:18 PM CET 
//


package org.opencb.commons.bioformats.network.psi.v253jaxb;

import javax.xml.bind.annotation.*;


/**
 * Describes the biological source of an object, in simple form only the NCBI taxid.
 * <p/>
 * <p>Java class for bioSourceType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="bioSourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="names" type="{net:sf:psidev:mi}namesType" minOccurs="0"/>
 *         &lt;element name="cellType" type="{net:sf:psidev:mi}openCvType" minOccurs="0"/>
 *         &lt;element name="compartment" type="{net:sf:psidev:mi}openCvType" minOccurs="0"/>
 *         &lt;element name="tissue" type="{net:sf:psidev:mi}openCvType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ncbiTaxId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bioSourceType", propOrder = {
        "names",
        "cellType",
        "compartment",
        "tissue"
})
@XmlSeeAlso({
        org.opencb.commons.bioformats.network.psi.v253jaxb.ExperimentType.HostOrganismList.HostOrganism.class,
        org.opencb.commons.bioformats.network.psi.v253jaxb.InteractorElementType.Organism.class,
        org.opencb.commons.bioformats.network.psi.v253jaxb.ParticipantType.HostOrganismList.HostOrganism.class
})
public class BioSourceType {

    protected NamesType names;
    protected OpenCvType cellType;
    protected OpenCvType compartment;
    protected OpenCvType tissue;
    @XmlAttribute(required = true)
    protected int ncbiTaxId;

    /**
     * Gets the value of the names property.
     *
     * @return possible object is
     *         {@link NamesType }
     */
    public NamesType getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     *
     * @param value allowed object is
     *              {@link NamesType }
     */
    public void setNames(NamesType value) {
        this.names = value;
    }

    /**
     * Gets the value of the cellType property.
     *
     * @return possible object is
     *         {@link OpenCvType }
     */
    public OpenCvType getCellType() {
        return cellType;
    }

    /**
     * Sets the value of the cellType property.
     *
     * @param value allowed object is
     *              {@link OpenCvType }
     */
    public void setCellType(OpenCvType value) {
        this.cellType = value;
    }

    /**
     * Gets the value of the compartment property.
     *
     * @return possible object is
     *         {@link OpenCvType }
     */
    public OpenCvType getCompartment() {
        return compartment;
    }

    /**
     * Sets the value of the compartment property.
     *
     * @param value allowed object is
     *              {@link OpenCvType }
     */
    public void setCompartment(OpenCvType value) {
        this.compartment = value;
    }

    /**
     * Gets the value of the tissue property.
     *
     * @return possible object is
     *         {@link OpenCvType }
     */
    public OpenCvType getTissue() {
        return tissue;
    }

    /**
     * Sets the value of the tissue property.
     *
     * @param value allowed object is
     *              {@link OpenCvType }
     */
    public void setTissue(OpenCvType value) {
        this.tissue = value;
    }

    /**
     * Gets the value of the ncbiTaxId property.
     */
    public int getNcbiTaxId() {
        return ncbiTaxId;
    }

    /**
     * Sets the value of the ncbiTaxId property.
     */
    public void setNcbiTaxId(int value) {
        this.ncbiTaxId = value;
    }

}
