//
// This path was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this path will be lost upon recompilation of the source schema.
// Generated on: 2010.03.15 at 03:58:18 PM CET 
//


package org.opencb.commons.bioformats.network.psi.v253jaxb;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * A interval on a sequence.
 * <p/>
 * <p>Java class for intervalType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="intervalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="begin" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="end" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "intervalType")
public class IntervalType {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger begin;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger end;

    /**
     * Gets the value of the begin property.
     *
     * @return possible object is
     *         {@link java.math.BigInteger }
     */
    public BigInteger getBegin() {
        return begin;
    }

    /**
     * Sets the value of the begin property.
     *
     * @param value allowed object is
     *              {@link java.math.BigInteger }
     */
    public void setBegin(BigInteger value) {
        this.begin = value;
    }

    /**
     * Gets the value of the end property.
     *
     * @return possible object is
     *         {@link java.math.BigInteger }
     */
    public BigInteger getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     *
     * @param value allowed object is
     *              {@link java.math.BigInteger }
     */
    public void setEnd(BigInteger value) {
        this.end = value;
    }

}
