//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 12:38:29 AM CEST 
//


package org.opencb.commons.bioformats.commons.parser.psi.v254jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * List of experiments in which this interaction has been determined.
 * 
 * <p>Java class for experimentList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="experimentList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="experimentRef" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="experimentDescription" type="{http://psi.hupo.org/mi/mif}experimentDescription"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "experimentList", propOrder = {
    "experimentRefOrExperimentDescription"
})
public class ExperimentList {

    @XmlElements({
        @XmlElement(name = "experimentRef", type = Integer.class),
        @XmlElement(name = "experimentDescription", type = ExperimentDescription.class)
    })
    protected List<Object> experimentRefOrExperimentDescription;

    /**
     * Gets the value of the experimentRefOrExperimentDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experimentRefOrExperimentDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperimentRefOrExperimentDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * {@link ExperimentDescription }
     * 
     * 
     */
    public List<Object> getExperimentRefOrExperimentDescription() {
        if (experimentRefOrExperimentDescription == null) {
            experimentRefOrExperimentDescription = new ArrayList<Object>();
        }
        return this.experimentRefOrExperimentDescription;
    }

}
