//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 12:38:29 AM CEST 
//


package org.opencb.javalibs.bioformats.network.psi.v254jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for experimentalInteractor complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="experimentalInteractor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="interactorRef" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;element name="interactor" type="{http://psi.hupo.org/mi/mif}interactor"/>
 *         &lt;/choice>
 *         &lt;element name="experimentRefList" type="{http://psi.hupo.org/mi/mif}experimentRefList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "experimentalInteractor", propOrder = {
        "interactorRef",
        "interactor",
        "experimentRefList"
})
public class ExperimentalInteractor {

    protected Integer interactorRef;
    protected Interactor interactor;
    protected ExperimentRefList experimentRefList;

    /**
     * Gets the value of the interactorRef property.
     *
     * @return possible object is
     *         {@link Integer }
     */
    public Integer getInteractorRef() {
        return interactorRef;
    }

    /**
     * Sets the value of the interactorRef property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setInteractorRef(Integer value) {
        this.interactorRef = value;
    }

    /**
     * Gets the value of the interactor property.
     *
     * @return possible object is
     *         {@link Interactor }
     */
    public Interactor getInteractor() {
        return interactor;
    }

    /**
     * Sets the value of the interactor property.
     *
     * @param value allowed object is
     *              {@link Interactor }
     */
    public void setInteractor(Interactor value) {
        this.interactor = value;
    }

    /**
     * Gets the value of the experimentRefList property.
     *
     * @return possible object is
     *         {@link ExperimentRefList }
     */
    public ExperimentRefList getExperimentRefList() {
        return experimentRefList;
    }

    /**
     * Sets the value of the experimentRefList property.
     *
     * @param value allowed object is
     *              {@link ExperimentRefList }
     */
    public void setExperimentRefList(ExperimentRefList value) {
        this.experimentRefList = value;
    }

}
