//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 12:38:29 AM CEST 
//


package org.opencb.javalibs.bioformats.network.psi.v254jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Describes molecules which have been used in specific experiments if these molecules are
 * different from the one listed as interactors. Example: The author of a paper makes a statement about
 * human proteins, but has really worked with mouse proteins. In this case the human protein would be the
 * main interactor, while the experimentalForm would be the mouse protein listed in this element.
 * Optionally this can refer to the experiment(s) in which this form has been used.
 * <p/>
 * <p/>
 * <p>Java class for experimentalInteractorList complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="experimentalInteractorList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="experimentalInteractor" type="{http://psi.hupo.org/mi/mif}experimentalInteractor" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "experimentalInteractorList", propOrder = {
        "experimentalInteractor"
})
public class ExperimentalInteractorList {

    @XmlElement(required = true)
    protected List<ExperimentalInteractor> experimentalInteractor;

    /**
     * Gets the value of the experimentalInteractor property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experimentalInteractor property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperimentalInteractor().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ExperimentalInteractor }
     */
    public List<ExperimentalInteractor> getExperimentalInteractor() {
        if (experimentalInteractor == null) {
            experimentalInteractor = new ArrayList<ExperimentalInteractor>();
        }
        return this.experimentalInteractor;
    }

}
