//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 12:38:29 AM CEST 
//


package org.opencb.javalibs.bioformats.network.psi.v254jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * A feature, e.g. domain, on a sequence.
 * <p/>
 * <p>Java class for feature complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="feature">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="names" type="{http://psi.hupo.org/mi/mif}names" minOccurs="0"/>
 *         &lt;element name="xref" type="{http://psi.hupo.org/mi/mif}xref" minOccurs="0"/>
 *         &lt;element name="featureType" type="{http://psi.hupo.org/mi/mif}cvType" minOccurs="0"/>
 *         &lt;element name="featureDetectionMethod" type="{http://psi.hupo.org/mi/mif}cvType" minOccurs="0"/>
 *         &lt;element name="experimentRefList" type="{http://psi.hupo.org/mi/mif}experimentRefList" minOccurs="0"/>
 *         &lt;element name="featureRangeList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="featureRange" type="{http://psi.hupo.org/mi/mif}baseLocation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attributeList" type="{http://psi.hupo.org/mi/mif}attributeList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "feature", propOrder = {
        "names",
        "xref",
        "featureType",
        "featureDetectionMethod",
        "experimentRefList",
        "featureRangeList",
        "attributeList"
})
public class Feature {

    protected Names names;
    protected Xref xref;
    protected CvType featureType;
    protected CvType featureDetectionMethod;
    protected ExperimentRefList experimentRefList;
    @XmlElement(required = true)
    protected Feature.FeatureRangeList featureRangeList;
    protected AttributeList attributeList;
    @XmlAttribute(required = true)
    protected int id;

    /**
     * Gets the value of the names property.
     *
     * @return possible object is
     *         {@link Names }
     */
    public Names getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     *
     * @param value allowed object is
     *              {@link Names }
     */
    public void setNames(Names value) {
        this.names = value;
    }

    /**
     * Gets the value of the xref property.
     *
     * @return possible object is
     *         {@link Xref }
     */
    public Xref getXref() {
        return xref;
    }

    /**
     * Sets the value of the xref property.
     *
     * @param value allowed object is
     *              {@link Xref }
     */
    public void setXref(Xref value) {
        this.xref = value;
    }

    /**
     * Gets the value of the featureType property.
     *
     * @return possible object is
     *         {@link CvType }
     */
    public CvType getFeatureType() {
        return featureType;
    }

    /**
     * Sets the value of the featureType property.
     *
     * @param value allowed object is
     *              {@link CvType }
     */
    public void setFeatureType(CvType value) {
        this.featureType = value;
    }

    /**
     * Gets the value of the featureDetectionMethod property.
     *
     * @return possible object is
     *         {@link CvType }
     */
    public CvType getFeatureDetectionMethod() {
        return featureDetectionMethod;
    }

    /**
     * Sets the value of the featureDetectionMethod property.
     *
     * @param value allowed object is
     *              {@link CvType }
     */
    public void setFeatureDetectionMethod(CvType value) {
        this.featureDetectionMethod = value;
    }

    /**
     * Gets the value of the experimentRefList property.
     *
     * @return possible object is
     *         {@link ExperimentRefList }
     */
    public ExperimentRefList getExperimentRefList() {
        return experimentRefList;
    }

    /**
     * Sets the value of the experimentRefList property.
     *
     * @param value allowed object is
     *              {@link ExperimentRefList }
     */
    public void setExperimentRefList(ExperimentRefList value) {
        this.experimentRefList = value;
    }

    /**
     * Gets the value of the featureRangeList property.
     *
     * @return possible object is
     *         {@link Feature.FeatureRangeList }
     */
    public Feature.FeatureRangeList getFeatureRangeList() {
        return featureRangeList;
    }

    /**
     * Sets the value of the featureRangeList property.
     *
     * @param value allowed object is
     *              {@link Feature.FeatureRangeList }
     */
    public void setFeatureRangeList(Feature.FeatureRangeList value) {
        this.featureRangeList = value;
    }

    /**
     * Gets the value of the attributeList property.
     *
     * @return possible object is
     *         {@link AttributeList }
     */
    public AttributeList getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     *
     * @param value allowed object is
     *              {@link AttributeList }
     */
    public void setAttributeList(AttributeList value) {
        this.attributeList = value;
    }

    /**
     * Gets the value of the id property.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(int value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="featureRange" type="{http://psi.hupo.org/mi/mif}baseLocation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "featureRange"
    })
    public static class FeatureRangeList {

        @XmlElement(required = true)
        protected List<BaseLocation> featureRange;

        /**
         * Gets the value of the featureRange property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the featureRange property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeatureRange().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link BaseLocation }
         */
        public List<BaseLocation> getFeatureRange() {
            if (featureRange == null) {
                featureRange = new ArrayList<BaseLocation>();
            }
            return this.featureRange;
        }

    }

}
