//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 12:38:29 AM CEST 
//


package org.opencb.javalibs.bioformats.network.psi.v254jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bioinfo.formats.parser.psi.v254jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EntrySet_QNAME = new QName("http://psi.hupo.org/mi/mif", "entrySet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bioinfo.formats.parser.psi.v254jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FullName }
     * 
     */
    public FullName createFullName() {
        return new FullName();
    }

    /**
     * Create an instance of {@link BaseLocation }
     * 
     */
    public BaseLocation createBaseLocation() {
        return new BaseLocation();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link ExperimentalInteractorList }
     * 
     */
    public ExperimentalInteractorList createExperimentalInteractorList() {
        return new ExperimentalInteractorList();
    }

    /**
     * Create an instance of {@link EntrySet }
     * 
     */
    public EntrySet createEntrySet() {
        return new EntrySet();
    }

    /**
     * Create an instance of {@link ExperimentalInteractor }
     * 
     */
    public ExperimentalInteractor createExperimentalInteractor() {
        return new ExperimentalInteractor();
    }

    /**
     * Create an instance of {@link Bibref }
     * 
     */
    public Bibref createBibref() {
        return new Bibref();
    }

    /**
     * Create an instance of {@link ParticipantIdentificationMethodList }
     * 
     */
    public ParticipantIdentificationMethodList createParticipantIdentificationMethodList() {
        return new ParticipantIdentificationMethodList();
    }

    /**
     * Create an instance of {@link ParticipantIdentificationMethod }
     * 
     */
    public ParticipantIdentificationMethod createParticipantIdentificationMethod() {
        return new ParticipantIdentificationMethod();
    }

    /**
     * Create an instance of {@link AvailabilityList }
     * 
     */
    public AvailabilityList createAvailabilityList() {
        return new AvailabilityList();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link BioSource }
     * 
     */
    public BioSource createBioSource() {
        return new BioSource();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link Names }
     * 
     */
    public Names createNames() {
        return new Names();
    }

    /**
     * Create an instance of {@link ExperimentalPreparation }
     * 
     */
    public ExperimentalPreparation createExperimentalPreparation() {
        return new ExperimentalPreparation();
    }

    /**
     * Create an instance of {@link InferredInteractionParticipant }
     * 
     */
    public InferredInteractionParticipant createInferredInteractionParticipant() {
        return new InferredInteractionParticipant();
    }

    /**
     * Create an instance of {@link HostOrganism }
     * 
     */
    public HostOrganism createHostOrganism() {
        return new HostOrganism();
    }

    /**
     * Create an instance of {@link HostOrganismList }
     * 
     */
    public HostOrganismList createHostOrganismList() {
        return new HostOrganismList();
    }

    /**
     * Create an instance of {@link ExperimentDescriptionList }
     * 
     */
    public ExperimentDescriptionList createExperimentDescriptionList() {
        return new ExperimentDescriptionList();
    }

    /**
     * Create an instance of {@link Alias }
     * 
     */
    public Alias createAlias() {
        return new Alias();
    }

    /**
     * Create an instance of {@link Xref }
     * 
     */
    public Xref createXref() {
        return new Xref();
    }

    /**
     * Create an instance of {@link ParticipantList }
     * 
     */
    public ParticipantList createParticipantList() {
        return new ParticipantList();
    }

    /**
     * Create an instance of {@link ExperimentalPreparationList }
     * 
     */
    public ExperimentalPreparationList createExperimentalPreparationList() {
        return new ExperimentalPreparationList();
    }

    /**
     * Create an instance of {@link ParameterList }
     * 
     */
    public ParameterList createParameterList() {
        return new ParameterList();
    }

    /**
     * Create an instance of {@link ConfidenceBase }
     * 
     */
    public ConfidenceBase createConfidenceBase() {
        return new ConfidenceBase();
    }

    /**
     * Create an instance of {@link ExperimentalRoleList }
     * 
     */
    public ExperimentalRoleList createExperimentalRoleList() {
        return new ExperimentalRoleList();
    }

    /**
     * Create an instance of {@link InteractorList }
     * 
     */
    public InteractorList createInteractorList() {
        return new InteractorList();
    }

    /**
     * Create an instance of {@link Interaction }
     * 
     */
    public Interaction createInteraction() {
        return new Interaction();
    }

    /**
     * Create an instance of {@link Availability }
     * 
     */
    public Availability createAvailability() {
        return new Availability();
    }

    /**
     * Create an instance of {@link ExperimentalRole }
     * 
     */
    public ExperimentalRole createExperimentalRole() {
        return new ExperimentalRole();
    }

    /**
     * Create an instance of {@link ConfidenceList }
     * 
     */
    public ConfidenceList createConfidenceList() {
        return new ConfidenceList();
    }

    /**
     * Create an instance of {@link Protein }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link InferredInteraction }
     * 
     */
    public InferredInteraction createInferredInteraction() {
        return new InferredInteraction();
    }

    /**
     * Create an instance of {@link OpenCvType }
     * 
     */
    public OpenCvType createOpenCvType() {
        return new OpenCvType();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ParameterBase }
     * 
     */
    public ParameterBase createParameterBase() {
        return new ParameterBase();
    }

    /**
     * Create an instance of {@link Feature.FeatureRangeList }
     * 
     */
    public Feature.FeatureRangeList createFeatureFeatureRangeList() {
        return new Feature.FeatureRangeList();
    }

    /**
     * Create an instance of {@link Participant }
     * 
     */
    public Participant createParticipant() {
        return new Participant();
    }

    /**
     * Create an instance of {@link FeatureList }
     * 
     */
    public FeatureList createFeatureList() {
        return new FeatureList();
    }

    /**
     * Create an instance of {@link ExperimentRefList }
     * 
     */
    public ExperimentRefList createExperimentRefList() {
        return new ExperimentRefList();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link ExperimentList }
     * 
     */
    public ExperimentList createExperimentList() {
        return new ExperimentList();
    }

    /**
     * Create an instance of {@link Confidence }
     * 
     */
    public Confidence createConfidence() {
        return new Confidence();
    }

    /**
     * Create an instance of {@link CvType }
     * 
     */
    public CvType createCvType() {
        return new CvType();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link AttributeList }
     * 
     */
    public AttributeList createAttributeList() {
        return new AttributeList();
    }

    /**
     * Create an instance of {@link Interactor }
     * 
     */
    public Interactor createInteractor() {
        return new Interactor();
    }

    /**
     * Create an instance of {@link InferredInteractionList }
     * 
     */
    public InferredInteractionList createInferredInteractionList() {
        return new InferredInteractionList();
    }

    /**
     * Create an instance of {@link Interactor.Organism }
     * 
     */
    public Interactor.Organism createInteractorOrganism() {
        return new Interactor.Organism();
    }

    /**
     * Create an instance of {@link InteractionList }
     * 
     */
    public InteractionList createInteractionList() {
        return new InteractionList();
    }

    /**
     * Create an instance of {@link DbReference }
     * 
     */
    public DbReference createDbReference() {
        return new DbReference();
    }

    /**
     * Create an instance of {@link ExperimentDescription }
     * 
     */
    public ExperimentDescription createExperimentDescription() {
        return new ExperimentDescription();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link EntrySet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://psi.hupo.org/mi/mif", name = "entrySet")
    public JAXBElement<EntrySet> createEntrySet(EntrySet value) {
        return new JAXBElement<EntrySet>(_EntrySet_QNAME, EntrySet.class, null, value);
    }

}
