//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 12:38:29 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psi.hupo.org/mi/mif", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package org.opencb.javalibs.bioformats.network.psi.v254jaxb;
