//
// This path was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this path will be lost upon recompilation of the source schema.
// Generated on: 2012.05.04 at 12:38:29 AM CEST 
//


package org.opencb.commons.bioformats.network.psi.v254jaxb;

import javax.xml.bind.annotation.*;


/**
 * Describes a molecular interactor.
 * <p/>
 * <p>Java class for interactor complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="interactor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="names" type="{http://psi.hupo.org/mi/mif}names"/>
 *         &lt;element name="xref" type="{http://psi.hupo.org/mi/mif}xref" minOccurs="0"/>
 *         &lt;element name="interactorType" type="{http://psi.hupo.org/mi/mif}cvType"/>
 *         &lt;element name="organism" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://psi.hupo.org/mi/mif}bioSource">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sequence" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="attributeList" type="{http://psi.hupo.org/mi/mif}attributeList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "interactor", propOrder = {
        "names",
        "xref",
        "interactorType",
        "organism",
        "sequence",
        "attributeList"
})
public class Interactor {

    @XmlElement(required = true)
    protected Names names;
    protected Xref xref;
    @XmlElement(required = true)
    protected CvType interactorType;
    protected Interactor.Organism organism;
    protected String sequence;
    protected AttributeList attributeList;
    @XmlAttribute(required = true)
    protected int id;

    /**
     * Gets the value of the names property.
     *
     * @return possible object is
     *         {@link Names }
     */
    public Names getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     *
     * @param value allowed object is
     *              {@link Names }
     */
    public void setNames(Names value) {
        this.names = value;
    }

    /**
     * Gets the value of the xref property.
     *
     * @return possible object is
     *         {@link Xref }
     */
    public Xref getXref() {
        return xref;
    }

    /**
     * Sets the value of the xref property.
     *
     * @param value allowed object is
     *              {@link Xref }
     */
    public void setXref(Xref value) {
        this.xref = value;
    }

    /**
     * Gets the value of the interactorType property.
     *
     * @return possible object is
     *         {@link CvType }
     */
    public CvType getInteractorType() {
        return interactorType;
    }

    /**
     * Sets the value of the interactorType property.
     *
     * @param value allowed object is
     *              {@link CvType }
     */
    public void setInteractorType(CvType value) {
        this.interactorType = value;
    }

    /**
     * Gets the value of the organism property.
     *
     * @return possible object is
     *         {@link Interactor.Organism }
     */
    public Interactor.Organism getOrganism() {
        return organism;
    }

    /**
     * Sets the value of the organism property.
     *
     * @param value allowed object is
     *              {@link Interactor.Organism }
     */
    public void setOrganism(Interactor.Organism value) {
        this.organism = value;
    }

    /**
     * Gets the value of the sequence property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSequence(String value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the attributeList property.
     *
     * @return possible object is
     *         {@link AttributeList }
     */
    public AttributeList getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     *
     * @param value allowed object is
     *              {@link AttributeList }
     */
    public void setAttributeList(AttributeList value) {
        this.attributeList = value;
    }

    /**
     * Gets the value of the id property.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(int value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://psi.hupo.org/mi/mif}bioSource">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Organism
            extends BioSource {


    }

}
