name: Reusable workflow to build Java application

on:
  workflow_call:
    inputs:
      maven_opts:
        type: string
        required: false
      build_folder:
        type: string
        required: false
        default: "build-folder"
      upload_artifact:
        type: boolean
        required: false
        default: false
      java_version:
        type: string
        required: false
        default: "11"
      storage_hadoop:
        type: string
        required: false
        default: "hdi5.1"
      dependency_repos:
        type: string
        required: false
        default: ""

jobs:
  build:
    uses: opencb/ci-core/.github/workflows/build.yml@main
    with:
      maven_opts: ${{ inputs.maven_opts }}
      build_folder: ${{ inputs.build_folder }}
      upload_artifact: ${{ inputs.upload_artifact }}
      java_version: ${{ inputs.java_version }}
      storage_hadoop: ${{ inputs.storage_hadoop }}
      dependency_repos: ${{ inputs.dependency_repos }}
