name: Compare vulnerabilities (Syft SBOM -> Grype) between two branches (robust)

on:
  workflow_dispatch:
    inputs:
      branch_a:
        description: 'First branch to compare (e.g. main)'
        required: true
        default: 'develop'
      branch_b:
        description: 'Second branch to compare (e.g. feature/fix-branch)'
        required: true
        default: ''

jobs:
  compare-sbom-grype:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: TASK-7908
          fetch-tags: true
      - name: Vulnerability Diff (Syft+Grype)
        uses: sec-open/vuln-diff-action@v1
        with:
          base_ref: ${{ github.event.inputs.branch_a }}
          head_ref: ${{ github.event.inputs.branch_b }}
          build_command: "mvn -q -DskipTests package"
          min_severity: "LOW"
          write_summary: "true"