name: Compare vulnerabilities (Syft SBOM -> Grype) between two branches (robust)

on:
  workflow_dispatch:
    inputs:
      branch_a:
        description: 'Base branch (e.g. develop)'
        required: true
        default: 'develop'
      branch_b:
        description: 'Head branch (e.g. TASK-1234)'
        required: true

jobs:
  compare-sbom-grype:
    runs-on: ${{ vars.UBUNTU_VERSION }}

    steps:
      # 1) Checkout only the HEAD branch
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_b }}
          fetch-depth: 0
          fetch-tags: true

      # 2) Explicitly fetch the BASE branch so it exists locally
      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.inputs.branch_a }}:refs/remotes/origin/${{ github.event.inputs.branch_a }}

      # 3) Run the vulnerability diff action
      - name: Vulnerability Diff (Syft+Grype)
        uses: sec-open/vuln-diff-action@v1
        with:
          # Use refs that are guaranteed to exist locally
          base_ref: refs/remotes/origin/${{ github.event.inputs.branch_a }}
          head_ref: ${{ github.sha }}  # safer than branch name to avoid worktree conflicts
          build_command: "mvn -q -DskipTests package"
          min_severity: "LOW"
          write_summary: "true"
          path: "."
