name: Compare vulnerabilities (Syft SBOM -> Grype) between two branches (robust)

on:
  workflow_dispatch:
    inputs:
      branch_a:
        description: 'First branch to compare (e.g. main)'
        required: true
        default: 'develop'
      branch_b:
        description: 'Second branch to compare (e.g. feature/fix-branch)'
        required: true
        default: ''

jobs:
  compare-sbom-grype:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - name: Vulnerability Diff (Syft+Grype)
        uses: sec-open/vuln-diff-action@v1
        with:
          base_ref: ${{ github.event.inputs.branch_a }}          # o la que quieras comparar como base
          head_ref: ${{ github.event.inputs.branch_b }}   # tu rama a comparar
          build_command: "mvn -q -DskipTests package"
          min_severity: "LOW"      # o HIGH si quieres ver solo HIGH/CRITICAL
          write_summary: "true"