name: Reusable workflow to push in DockerHub

on:
  workflow_call:
    inputs:
      cli:
        type: string
        required: true
      repository:
        type: string
        required: false
      branch:
        type: string
        required: false
      build_folder:
        type: string
        required: false
        default: "build-folder"
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  deploy-docker-hub:
    name: Push Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout optional repo"
        uses: actions/checkout@v4
        if: inputs.repository != '' && inputs.branch != ''
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_folder }}
          path: build
      - name: Chmod
        run: "find build -regex '.*sh' | while read file ; do chmod u+x $file ; done"
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Deploy in Docker Hub
        run: ${{ inputs.cli }}
