# This workflow deploys a Maven project to Sonatype Central using a reusable action.
name: Reusable Sonatype Central Deployment

on:
  workflow_call:
    inputs:
      maven_opts:
        description: 'Additional Maven CLI options (optional)'
        type: string
        required: false
    secrets:
      MAVEN_NEXUS_USER:
        description: 'Sonatype Central username (token)'
        required: true
      MAVEN_NEXUS_PASSWORD:
        description: 'Sonatype Central password (token)'
        required: true
      MAVEN_GPG_PRIVATE_KEY:
        description: 'Base64-encoded GPG private key'
        required: true
      MAVEN_GPG_PASSPHRASE:
        description: 'Passphrase for your GPG key'
        required: true

jobs:
  deploy:
    name: Deploy to Sonatype Central
    runs-on: ubuntu-22.04
    env:
      # Allow GPG to access a TTY if needed
      GPG_TTY: ${{ runner.tool_cache }}/workspace/.gpg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history so tags and versions are available
          fetch-depth: 10

      - name: Set up Java 8 & Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'        # Eclipse Temurin JDK
          java-version: '8'              # Java 8 compatibility
          cache: 'maven'                 # Cache dependencies

      - name: Import GPG private key
        # Decode and import your Base64-encoded private key
        env:
          GPG_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          echo "$GPG_KEY" | base64 -d > private.key
          gpg --batch --import private.key
          rm private.key

      - name: Generate Maven settings.xml
        # Create settings.xml with Sonatype Central credentials & GPG profile
        run: |
          cat > settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.MAVEN_NEXUS_USER }}</username>
                <password>${{ secrets.MAVEN_NEXUS_PASSWORD }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>gpg</id>
                <properties>
                  <gpg.passphrase>${{ secrets.MAVEN_GPG_PASSPHRASE }}</gpg.passphrase>
                </properties>
              </profile>
            </profiles>
          </settings>
          EOF

      - name: Deploy to Central
        # A single Maven deploy picks SNAPSHOT vs Release by your POM’s version
        run: mvn clean deploy -DskipTests -s settings.xml ${{ inputs.maven_opts }} --no-transfer-progress
