name: Merge/Push in java-common-libs develop branch

on:
  push:
    branches:
      - develop
      - release-*

jobs:
  build:
    uses: ./.github/workflows/build-java-app-workflow.yml

  deploy-maven:
    uses: ./.github/workflows/deploy-maven-repository-workflow.yml
    needs: build
    secrets: inherit
