name: Push java-common-libs develop

on:
  push:
    branches:
      - TASK-*

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop

  sonar:
    uses: opencb/java-common-libs/.github/workflows/sonar-analysis-workflow.yml@develop
    needs: build
    with:
      sonarProjectKey: opencb_java-common-libs
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Test java-common-libs
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        mongodb: ["4.2"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '10'
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Start MongoDB v${{ matrix.mongodb }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
          mongodb-replica-set: rs-test
      - name: Run Maven Tests
        run: mvn -T 2 clean install -DskipTests
