name: Push in java-common-libs task branch

on:
  push:
    branches:
      - TASK-*

jobs:
  build:
    uses: ./.github/workflows/build-java-app-workflow.yml

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit

  test-xetabase:
    name: "Run all tests before merging"
    uses: ./.github/workflows/test-xetabase-workflow.yml
    with:
      branch: TASK-8067
      task: TASK-8067
    secrets: inherit


  test-pull-request-approve:
    uses: opencb/ci-core/.github/workflows/pull-request-approve.yml@main
    with:
      target_branch: develop
      head_ref: TASK-8067
    secrets: inherit