name: Push in java-common-libs task branch

on:
  push:
    branches:
      - TASK-*

jobs:
  build:
    uses: ./.github/workflows/build-java-app-workflow.yml

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit
