name: Pull request approve workflow
run-name: 'Pull request approve workflow ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} by @${{ github.actor }}'

on:
  push:
    branches:
      - TASK-*


jobs:
  calculate-xetabase-branch:
    name: Calculate Xetabase branch
    runs-on: ubuntu-22.04
    outputs:
      xetabase_branch: ${{ steps.get_xetabase_branch.outputs.xetabase_branch }}
    steps:
      - name: Clone java-common-libs
        uses: actions/checkout@v4
        with:
          fetch-depth: '10'
      - id: get_xetabase_branch
        name: "Get current branch for Xetabase from target branch"
        run: |
          if [ "$( git ls-remote https://github.com/opencb/opencga.git "TASK-6807" )" ] ; then
           echo "OPENCGA TASK-6807 branch";
          fi
          
          if [ "$(git ls-remote "https://$ZETTA_REPO_ACCESS_TOKEN@github.com/zetta-genomics/opencga-enterprise.git" "$input_branch" )" ] ; then
            echo "Here it is TASK-6807 branch";
          fi
          chmod +x ./.github/workflows/scripts/get-xetabase-branch.sh
          echo "secrets.ZETTA_REPO_ACCESS_TOKEN: ${{ secrets.ZETTA_REPO_ACCESS_TOKEN }}" | tee -a ${GITHUB_STEP_SUMMARY}
          xetabase_branch=$(./.github/workflows/scripts/get-xetabase-branch.sh "TASK-6807" )
          echo "__Xetabase ref:__ \"${xetabase_branch}\"" | tee -a ${GITHUB_STEP_SUMMARY}
          echo "xetabase_branch=${xetabase_branch}" >> $GITHUB_OUTPUT
        env:
          ZETTA_REPO_ACCESS_TOKEN: ${{ secrets.ZETTA_REPO_ACCESS_TOKEN }}
  test:
    name: "Run all tests before merging"
    needs: calculate-xetabase-branch
    uses: opencb/java-common-libs/.github/workflows/test-xetabase-workflow.yml@develop
    with:
      branch: ${{ needs.calculate-xetabase-branch.outputs.xetabase_branch }}
      task: TASK-6807
    secrets: inherit