//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:58:18 PM CET 
//


package org.opencb.commons.bioformats.commons.parser.psi.v253jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * A list of confidence values.
 * 
 * <p>Java class for confidenceListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="confidenceListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="confidence" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{net:sf:psidev:mi}confidenceType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="experimentRefList" type="{net:sf:psidev:mi}experimentRefListType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "confidenceListType", propOrder = {
    "confidence"
})
public class ConfidenceListType {

    @XmlElement(required = true)
    protected List<Confidence> confidence;

    /**
     * Gets the value of the confidence property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the confidence property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfidence().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfidenceListType.Confidence }
     *
     *
     */
    public List<Confidence> getConfidence() {
        if (confidence == null) {
            confidence = new ArrayList<Confidence>();
        }
        return this.confidence;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{net:sf:psidev:mi}confidenceType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="experimentRefList" type="{net:sf:psidev:mi}experimentRefListType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "experimentRefList"
    })
    public static class Confidence
        extends ConfidenceType
    {

        protected ExperimentRefListType experimentRefList;

        /**
         * Gets the value of the experimentRefList property.
         * 
         * @return
         *     possible object is
         *     {@link ExperimentRefListType }
         *     
         */
        public ExperimentRefListType getExperimentRefList() {
            return experimentRefList;
        }

        /**
         * Sets the value of the experimentRefList property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExperimentRefListType }
         *     
         */
        public void setExperimentRefList(ExperimentRefListType value) {
            this.experimentRefList = value;
        }

    }

}
